"""The tab-separated reader/writer every table in notes/ uses.

Four writer shapes exist in the corpus and they are not interchangeable, so the package
provides them by name rather than picking one and rewriting generated bytes:

  write_rows  "\\t".join(str(v).replace(tab, " ").replace(newline, " "))  -> catalog.tsv, index tables
  write_csv   csv.writer(delimiter="\\t", lineterminator="\\n")           -> sources.tsv, abstracts.tsv
  write_plain "\\t".join(str(v))                                          -> formalization-deps.tsv
  write_sanitized "\\t".join(str(v).replace(tab, " "))                   -> links.tsv

write_csv quotes a cell that contains the delimiter; the join writers do not, which is why
the join writers sanitize instead. A reader that parses with split(',') reads every
tab-delimited table as one field.
"""

from __future__ import annotations

import csv
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path


def cell(value: object) -> str:
    """A cell as the join writers emit it: tabs and newlines folded to spaces."""
    return str(value).replace("\t", " ").replace("\n", " ")


def read_rows(path: Path) -> list[dict[str, str]]:
    """Rows as dicts. delimiter='\\t' is not optional on these files."""
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def read_rows_from_text(text: str) -> list[dict[str, str]]:
    """Rows as dicts from text already in memory (the read-once-and-reuse pattern)."""
    return list(csv.DictReader(text.splitlines(), delimiter="\t"))


def read_matrix(path: Path) -> tuple[list[str], list[list[str]]]:
    """Header fields and raw rows, for a reader that indexes by column position."""
    with path.open(encoding="utf-8") as fh:
        rdr = csv.reader(fh, delimiter="\t")
        fields = next(rdr, [])
        return fields, [r for r in rdr if r]


def write_rows(path: Path, cols: Sequence[str], rows: Iterable[Mapping[str, object]]) -> None:
    """Header line plus one line per row, cells folded by cell()."""
    with path.open("w", encoding="utf-8") as fh:
        fh.write("\t".join(cols) + "\n")
        for r in rows:
            fh.write("\t".join(cell(r[c]) for c in cols) + "\n")


def write_csv(path: Path, cols: Sequence[str], rows: Iterable[Mapping[str, object]]) -> None:
    """csv.writer form: a cell containing the delimiter is quoted."""
    with path.open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, delimiter="\t", lineterminator="\n")
        w.writerow(cols)
        for r in rows:
            w.writerow([r[c] for c in cols])


def write_plain(path: Path, cols: Sequence[str], rows: Iterable[Mapping[str, object]]) -> None:
    """Unsanitized join: the writer that produced formalization-deps.tsv."""
    with path.open("w", encoding="utf-8") as fh:
        fh.write("\t".join(cols) + "\n")
        for r in rows:
            fh.write("\t".join(str(r[c]) for c in cols) + "\n")


def write_sanitized(path: Path, cols: Sequence[str], rows: Iterable[Mapping[str, object]]) -> None:
    """Tab-only fold: the writer that produced links.tsv."""
    with path.open("w", encoding="utf-8") as fh:
        fh.write("\t".join(cols) + "\n")
        for r in rows:
            fh.write("\t".join(str(r[c]).replace("\t", " ") for c in cols) + "\n")
